### ISSUE TITLE
ETIMEDOUT on fetching names

### ISSUE THREAD

**Issue by olivif** [IonicaBizau/namly#2] opened 2015-12-18 10:57 UTC
Ran 

```
$ namly -i crawl
```

and I'm getting an ETIMEDOUT every time. 

I also ran a script similar to the one in example and that failed with the same error once and succeeded once. 

![namly-err](https://cloud.githubusercontent.com/assets/7736961/11895315/0d9ccd50-a57e-11e5-97ef-df89bc3f0d74.png)

**Comment by IonicaBizau** [comment] 2015-12-19 15:05
@olivif Hmm, interesting.

Can you check if [`tinyreq`](https://github.com/IonicaBizau/tinyreq) works smoothly on Windows?

https://github.com/IonicaBizau/tinyreq#installation

I wonder if that's the problem, otherwise we will go from highest level to the lowest. :smile:

**Comment by olivif** [comment] 2015-12-19 15:11
tinyreq seems to be working, I ran the example from https://github.com/IonicaBizau/tinyreq#installation and got content :)

**Comment by IonicaBizau** [comment] 2015-12-19 15:16
@olivif Great! Can you run the example from [`npm-available-array`](https://github.com/IonicaBizau/npm-available-array)?

**Comment by olivif** [comment] 2015-12-19 15:40
This looks pretty good too 

![image](https://cloud.githubusercontent.com/assets/7736961/11913750/350e4f48-a66f-11e5-84a3-f2092d2cc571.png)

**Comment by olivif** [comment] 2015-12-19 15:42
@IonicaBizau interestingly enough, I ran namly again now (same input as before) and it started working. can it be a dependencies thing?

**Comment by IonicaBizau** [comment] 2015-12-19 15:59
@olivif `ETIMEDOUT` simply means that the request to the `npm` registry took longer than the default timeout which probably means they had some lag. :hourglass: 

But glad to hear the problem is fixed. :joy: 

Could it be also the internet connection?

**Comment by olivif** [comment] 2015-12-19 16:09
Hmm interesting. What seems odd to me is that it worked from my test index.js but not from the cmd. And I ran both at the same time, same machine, with the same input. 

Feel free to close though, seems to be working now :8ball:

**Comment by IonicaBizau** [comment] 2015-12-19 16:10
@olivif Did it happen multiple times over the day? Maybe they were redeploying the app. :grin:
Closing for now, feel free to ping with more information in case that happens again.

**Closed as completed by IonicaBizau** 2015-12-19 16:10 UTC
Labels: bug

**Comment by olivif** [comment] 2015-12-19 16:12
@IonicaBizau thanks for helping investigate! Yes, it was definitely something intermittent and most likely not related to the namly code. Will ping back if it happens again :)
